### PR TITLE
README Polish

### PR DESCRIPTION
**Pull request by adamkaplan**

### CODE REVIEW

**Comment by dbgrandi** [comment]
Ready says Apache, `LICENSE` says MIT.

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by dbgrandi** [comment]
s/Ready/README/

**Comment by adamkaplan** [comment]
Nice eye. Copied from `YMPromptKit`

**Comment by adamkaplan** [comment]
Killing this because the commit list is absurd. Rebased into #3

**Pull request closed without merging**
