### PR TITLE
Fixing objc code blocks and removed tracking pixels

### PR DESCRIPTION
**Pull request by ghv**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by ghv** [comment]
I signed the CLA after I created this PR.

**Comment by adamkaplan** [comment]
Yeah. The thing is part of the build failed so I can’t merge it due to the strict default restrictions on the Yahoo public repos. It’s a permissions error due to a fork so I should really fix the build to allow easier contributions.

**Comment by ghv** [comment]
@gyehuda, any chance you could assist us here? Thanks!

**Comment by adamkaplan** [comment]
Apologies! Had a child recently and all the pre-paternity stuff got sort of left behind :P

**Pull request merged**
