### PR TITLE
Update version to 2.0.0

### PR DESCRIPTION
**Pull request by adamkaplan**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by adamkaplan** [comment]
The public API changes are refinements. Also, one integer sign change, but it was documented to behave the updated fashion.

The initializer aborts instead of nils – I'm torn on whether that's a breaking change because previously it _was broken_, now it lets you know that it's broken much faster. If it "breaks" integration with a client, it's because that client's implementation was actually broken already!

**Comment by dbgrandi** [comment]
There are two points I'd look at to answer if it should be a major version...

Are there any warnings that could be triggered from the changes to the integer sign on that one method? If you get any warnings and have warnings == errors, then it requires a code change in how it's integrated.

If somebody had YMCache integrated in a feature that they didn't notice being broken when the file path was wrong, and updates this because it's a patch release, they are suddenly going to have a lot of crashes. While it did not change the public API signature, it changes the public API behavior in a very real way.

**Comment by dbgrandi** [comment]
Also, needs some CHANGELOG love.

**Comment by adamkaplan** [comment]
Yeah

**Pull request merged**
