### PR TITLE
Feature/swift native

### PR DESCRIPTION
**Pull request by Amosel**
This PR seem to pass all tests. What's new in it is that the swift implementation is also tested.
I am not sure why but test target is not able to find the <YMCache/YMCache-Swift.h>. I also tried referring the generated umbrella file form the YMCache.h file, that didn't work too.

I had to reconfigure and restructured the xcproj while trying to get the test target to work.
Eventually when I gave up, I simply wrote a Shim ObjC objet that internally uses the swift implementation.
After I pushed the PR I the travis CI was failing because the travis file were never added after the project got restructured and all Mac test target wasn't recreated yet.

I added the travis files and commented the statements for the Mac OS X test target.

### CODE REVIEW

**Comment by adamkaplan** [comment]
Awesome, thanks @Amosel!

We'll do a code review over the coming days @ Yahoo because YMCache is a seriously critical cog in our iOS machine.

Probably don't need to worry about Travis for now. It won't pass for you. The build keys are only valid for PRs originating from the main repo.

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by Amosel** [comment]
I reverted back to #ba4c7de and build up from there. Ive got now the same result but without messing up the project. I will have to rewrite history on my fork and resubmit the PR.

**Comment by adamkaplan** [comment]
This is likely the base branch for 2.0.0

**Comment by dbgrandi** [comment]
With over a year passing, I'm closing this. Feel free to re-open.

**Pull request closed without merging**
